<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (self $model) {
            $model->slug = Str::slug($model->name);
        });
    }

    public function posts(): BelongsToMany
    {
        return $this->belongsToMany(Post::class, 'posts_categories');
    }
}
